# # These genres will always be rejected from the playlist
# reject = [
#     "afro r&b",
#     "alternative country",
#     "alternative r&b",
#     "arkansas country",
#     "atl hip hop",
#     "ccm",
#     "chicago drill",
#     "chill r&b",
#     "christian",
#     "corrido",
#     "electro latino",
#     "funk",
#     "gospel",
#     "indie r&b",
#     "kentucky indie",
#     "latin",
#     "venezolano",
#     "reggaeton",
#     "rap",
#     "trap",
#     "pluggnb",
#     "progressive house",
#     "puerto rican",
#     "hip hop",
#     "r&b",
# ]

# # These artists will always be allowed into the playlist, regardless of rejected genres
# accept = [
#     "Bad Bunny",
#     "Kodak Black",
#     "Kanye West",
#     "Kid Cudi",
#     "Doja Cat",
#     "Kendrick Lamar",
#     "Cardi B",
#     "Weezer",
# ]
